合併完Ｗendy的code
drmobile/SociusAppium pull request #12
Opened 2017-08-11 02:15 UTC by ask2012352

合併Ｗendy的code 並且全部的 test case皆重新跑過，都可順利執行
執行時注意事項 ：
1.config.py 需加上 VIEDO_PHOTO__DIR_PATH = "檔案路徑/test_resources/."
2.若執行之手機版本(目前發現Android 5.0.2)有海帶條，在執行PostsTests時，需要先刪除分享貼文()

2017-08-11 04:13 UTC, jonascheng requested changes

2017-08-11 04:13 UTC, jonascheng commented on RAT.py
> +    subprocess.Popen(['adb','push', '*.mp4', '/sdcard/Soocii'])
這是不小心加到的嗎？

2017-08-11 04:13 UTC, jonascheng commented on RAT.py
> +    subprocess.Popen(['adb', 'push', config.VIEDO_PHOTO__DIR_PATH, '/sdcard/Soocii/'])
放在config主要是帳號密碼或會需要常變動的設定, ex: soocii apk

這個參數不會變，也跟的github repo, 可以直接使用沒關係

2017-08-11 04:13 UTC, jonascheng commented on RAT.py
> +            self.sociushelper.click_login_by_email_link()
你這邊跟Wendy登入方式不伊樣，避免每次改來改去，要不全部都用email登入？

2017-08-11 07:26 UTC, ask2012352 commented on RAT.py
> +    subprocess.Popen(['adb','push', '*.mp4', '/sdcard/Soocii'])
是的 沒刪除到...

2017-08-12 03:34 UTC, jonascheng approved these changes

2017-08-12 03:34 UTC, jonascheng commented on RAT.py
> +            print "cccccccc :" +os.path.abspath(path1)
這次我先merge, 下次不要放沒有意義的print

(我知道你在測試執行的output)

2017-08-12 03:34 UTC, merged